### ISSUE TITLE
Wrong nuget-package references

### ISSUE THREAD

**Issue by FatkullinT** [epam/sitecore-engx-scaffold#19]
Tests project generated by the "sitecore-engx-scaffold:module" command refers on wrong versions of nuget-packages:

  _package id="Sitecore.Abstractions" version="12.0.0" 
  package id="Sitecore.Analytics" version="12.0.0"
  package id="Sitecore.Analytics.Core" version="12.0.0"
  package id="Sitecore.Analytics.DataAccess" version="12.0.0" 
  package id="Sitecore.Analytics.Model" version="12.0.0" 
  package id="Sitecore.ContentSearch" version="4.0.0" 
  package id="Sitecore.ContentSearch.Linq" version="4.0.0" 
  package id="Sitecore.Kernel" version="12.0.0"
  package id="Sitecore.Logging" version="12.0.0"
  package id="Sitecore.Logging.Client" version="12.0.0"
  package id="Sitecore.Mvc" version="3.0.0"
  package id="Sitecore.NVelocity" version="9.0.0" 
  package id="Sitecore.Zip" version="12.0.0"_ 

Most of these packages are not exist. Module has been created for Sitecore 9.1.1.

**Comment by ashishagin** [comment]
Hi Timur, good finding, thanks!

We will provide a fix for that very soon.

**Comment by ashishagin** [comment]
resolved in #23
